---
title: "Rmarkdown-Thesis-GitHub"
author: "Parviz Shahmirzalou, PhD Candidate."
date: "2023-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r directory, include=FALSE}
# Set Working directory. Write your computer working directory similar to below.
knitr::opts_knit$set(root.dir = 'C:/Users/Lenovo/Documents')
```


## 2- Run Bayesian Approach with Birnbaum-Saunders distribution.

###  Scenario: "t ~ BS(2,4), c ~ Exp(0.02), p=0.20, n=200"

### 2-1 R codes:

```{r}
{
  rm(list = ls())
  library(survival)
  library(R2OpenBUGS)
  # Set working directory and modelfile.
  getwd()
  bugswd = paste0(getwd(),"/bugswd"); bugswd
  modelfile = paste0(bugswd,"/modelfile.txt"); modelfile
  
  # generate Data
  set.seed(12345)
  n = 200 # n=100; 200; 300
  x = rep(0:1, c(0.50*n, 0.50*n))  # BS scale parameter related to x.
  table(x)
  shape = 2    # Shape: 0.5; 1; 2                   
  b = c(1, 0.65)  # set b1 and b2 with table 4 in paper.
  lambda = exp(b[1] + b[2]*x)
  summary(lambda)
  scale = lambda             
  # Define rbn to generate numbers from BS distribution.
  rbn <- function(n, shape, scale){    # shape = a, scale = b
    x <- rnorm(n, 0, shape/2)
    t <- scale * (1 + 2 * x^2 + 2 * x * sqrt(1 + x^2))
    return(t)
  }
  #Generate Observed time
  y <- rbn(n, shape, lambda)
  # Generate censored time
  delta1 = rep(1,n)
  cen = rexp(n,0.021)   # repeat to get 20% censoring.
  delta = as.numeric(y < cen)
  cenper = 1 - mean(delta); cenper   # % censoring
  # Merge observed and censored time.
  
  z = pmin(y,cen)
  # make variable "t" as observed time and variable "c" as censored time to use in BUGS.
  t <- ifelse(delta == 1, z, NA)
  c <- ifelse(delta == 1, 0, z)
  # Run model in BUGS.
  # model---------------------------------------- this part is write as BUGs code
  modeltext = "model {
  for(i in 1:n){
	  t[i] ~ dbs(shape, lambda[i])C(c[i], )
	  log(lambda[i]) <- b[1]+b[2]*x[i]
  
  
  cim[i] <- step(c[i]-1.0E-5) * lambda[i] * pow( (shape/2) * 0.5875441*logit(0.5 + 0.5 * phi((1/shape) * 
            (sqrt(c[i]/lambda[i]) - sqrt(lambda[i]/c[i])))) + sqrt( 1 + pow( (shape/2) * 
            0.5875441 * logit(0.5 + 0.5 * phi((1/shape) * (sqrt(c[i]/lambda[i]) -
            sqrt(lambda[i]/c[i])))),2)) ,2)
  
  }
	# priors
	shape ~ dgamma(0.01,0.01)
	for(j in 1:2) {b[j]~dnorm(0,0.01)}		
  }
  "
  cat(modeltext, file = modelfile) #file.show(modelfile)
  modeldata = list(n = n, x = x, t = t, c = c)
  modelinit = list(list(b = rep(0,length(b)), shape = shape))
  
  param = c("shape","b","cim")
  # bugs ----------------------------------------
  bugsOut <- bugs(
    working.directory = bugswd,
    model.file = modelfile,
    data = modeldata,
    inits = modelinit,
    #inits = NULL,
    parameters.to.save = param,
    n.chains = 1,
    n.iter = 11000,
    n.burnin = 1000,
    n.thin = 1
    #, debug = TRUE
    #, codaPkg = TRUE
  )
  # output ----------------------------------------
  bugsOut$DIC
  ic = which(delta==0); ic
  dim(bugsOut$sims.array)
  bugsOut$summary[c(1:3,3+ic),c(1,2)]  #3+ic means that after third row show rows given ic(censored data).
  parsim = bugsOut$sims.array[,1,1:3]   #parameter simulation
  impsim = bugsOut$sims.array[,1,3+ic]  # imputation simulation: cim=exp(b1+b2*x), x=0,1
  mean(impsim[3,])
  
  small = as.numeric(impsim[ic]<z[ic])
  test = data.frame("True" = z[ic], "simulated" = impsim[ic], "small" = small, "ic" = ic)
  #View(test)
  smallimpper = mean(small); smallimpper   # Simulated<True
  timp = t
}  
```

### 2-2 figure 3-25(H) in the thesis. 

```{r}
{
  # Kaplan-Meier Curve:
  curve1 = survfit(Surv(z,delta) ~ x); curve1
  plot(curve1, mark.time = TRUE,lty = 1,conf.int = FALSE,  col = "black",
       main = paste("H                            t~BS(2,4), c~Exp(0.02), p=0.20, n=200") )  #KM_Estimation
  # Curve with Median of Simulated Times
  # output ----------------------------------------
  # imputation      h=hat
  bh = bugsOut$mean$b; bh
  shapeh = bugsOut$mean$shape; shapeh
  lambdah = exp(bh[1] + bh[2]*x); lambdah #every person has specific lambda because it has specific X.
  scaleh = lambdah; scaleh
  
  #install.packages("extraDistr")
  library(extraDistr)
  # Compute median of Simulations.
  zmed = qfatigue(.5*pfatigue(cen,shapeh,scaleh, mu = 0, lower.tail = FALSE),shapeh, scaleh,mu = 0, lower.tail = FALSE)
  zmed
  # Make a variable include median of simulations.
  zimp = rep(NA,n)
  zimp[ic] = zmed[ic]
  zimp[-ic] = z[-ic]  # zimp = failure times+imputed censored times
  
  
  #
  curve2 = survfit(Surv(zimp,delta1) ~ x); curve2
  lines(curve2, mark.time = TRUE, col = "Blue", lty = 1)
  
  #Curve without Censored Times 
  tOC = z[delta==1]
  deltaOC = rep(1, length(tOC))
  curve3 = survfit(Surv(tOC, deltaOC) ~ x[delta==1]); curve3
  lines(curve3, mark.time = TRUE, col = "Red", lty = 1)
  
  legend("topright", c("Kaplan-Meier Curve", "Curve with Median of Simulated Times", "Curve without Censored Times"),
         lty= 1, col = c("black", "Blue", "Red"), cex = 0.7)
  
}
```

### 2-3  figure 3-27(B) in the thesis.

```{r}
{
  # Kaplan-Meier Curve:  
  curve1 = survfit(Surv(z,delta) ~ x); curve1
  plot(curve1, mark.time = TRUE,lty = 1, lwd = 2, col = "black", 
       main = paste("B                            t~BS(2,4), c~Exp(0.02), p=0.20, n=200"))  #KM_Estimation
  
  # Curve for 10,000 Times Imputation
  timp=t
  impsim = bugsOut$sims.array[,1,3+ic]  
  for (i in 1:nrow(impsim)) {
    timp[ic] <- impsim[i,]
    kmi = survfit(Surv(timp,delta1) ~ x)
    lines(kmi, mark.time = TRUE, col = "gray", lty = 1)    # n time Imputation
    
  }
  # Curve for Imputations Mean
  timp[ic] <- colMeans(impsim)
  kmmean = survfit(Surv(timp,delta1) ~ x)
  lines(kmi, mark.time = TRUE, col = "blue", lty = 2, lwd = 2)  # Mean of n times Imputation
  
  lines(curve1, mark.time = TRUE,lty = 1, lwd = 2, col = "black", 
        main = paste("t~BS(2,4), c~Exp(0.01), p=0.10, n=200"))  #KM_Estimation
  
  
  legend("topright", 
         c("Kaplan-Meier Curve", "Curve for 10,000 times Imputation", "Curve for Imputations Mean"),
         lty = 1, col = c("Black", "gray","blue"), cex = .7)
  
  
}
```
