---
title: "Rmarkdown-Thesis-GitHub"
author: "Parviz Shahmirzalou, PhD Candidate."
date: "2023-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r directory, include=FALSE}
# Set Working directory. Write your computer working directory similar to below.
knitr::opts_knit$set(root.dir = 'C:/Users/Lenovo/Documents')
```

## 1- Run Bayesian Approach with Weibull distribution.




### Scenario: "t ~ Weibull(2,4), c ~ Exp(0.02), p=0.20, n=200"

### 1-1 R codes:

```{r}
{
  rm(list = ls())
  # Install packages:survival & R2openBUGS.
  library(survival)
  library(R2OpenBUGS)
  # Set working directory and modelfile.
  getwd()
  bugswd = paste0(getwd(),"/bugswd"); bugswd
  modelfile = paste0(bugswd,"/modelfile.txt"); modelfile
  # Generate Data
  set.seed(12345)
  n = 200  # n=100; 200; 300
  x = rep(0:1, c(0.50*n, 0.50*n))  # Weibull scale parameter related to x.
  table(x)
  shape = 2  # Shape: 0.5; 1; 2
  b = c(-3.2, 1) # set b1 and b2 with table 2 in paper.
  lambda = exp(b[1] + b[2]*x)   # Link the parameter to covariate x .
  summary(lambda)
  scale = lambda^(-1/shape)   # Since weibull formulla in winbugs is different to R, we need to convert
  # formula to get similar results.
  summary(scale)   # Mean scale parameter is near to 4.
  #Generate Observed time
  y = rweibull(n,shape, scale )    
  summary(y)
  range(y)
  # Generate censored time
  delta1 = rep(1,n)   # to make censored data
  cen = rexp(n,0.06)             # Censored time
  delta = as.numeric(y < cen)
  cenper = 1 - mean(delta); cenper   # Get percent of censoring
  # Merge observed and censored time.
  z = pmin(y,cen)  # to select observed time or censored time. Every one that is lesser than other.
  # make variable "t" as observed time and variable "c" as censored time to use in BUGS.
  t <- ifelse(delta == 1, z, NA)
  c <- ifelse(delta == 1, 0, z)
  # Run model in BUGS.
  modeltext = "model {
      for(i in 1:n){
        t[i] ~ dweib(shape,lambda[i])C(c[i], )
      	log(lambda[i]) <- b[1]+b[2]*x[i]
        cim[i] <- step(c[i]-1.0E-5)*pow(log(2)/lambda[i]+pow(c[i],shape), 1/shape)
        }
      	# priors
      	shape ~ dgamma(0.01,0.01)  # Non-informative prior
      	for(j in 1:2) {b[j]~dnorm(0,0.01)}		
      }
      "
  # write BUGS output into file.
  cat(modeltext, file = modelfile) #file.show(modelfile)
  modeldata = list(n = n, x = x, t = t, c = c)
  modelinit = list(list(b = rep(0,length(b)), shape = shape))
  param = c("shape","b","cim")
  # bugs ----------------------------------------
  bugsOut <- bugs(
    working.directory = bugswd,
    model.file = modelfile,
    data = modeldata,
    inits = modelinit,
    #inits = NULL,
    parameters.to.save = param,
    n.chains = 1,
    n.iter = 11000,
    n.burnin = 1000,
    n.thin = 10
    #, debug = TRUE
    #, codaPkg = TRUE
  )
  # output ----------------------------------------
  bugsOut$DIC
  # Which records is censored:
  ic = which(delta==0); ic; length(ic)
  # Dimension of output:
  dim(bugsOut$sims.array)
  # Describe censored simulations.
  bugsOut$summary[c(1:3,3+ic),c(1,2)] 
  # Describe parameter simulations:
  parsim1 = bugsOut$sims.array[,1,1:3]   #parameter simulation
  parsim1[1:5,]  # Only five rows of 10.000 simulation for parameters.
  # print median of simulations for every censor that replaced.
  bugsOut$median$cim[ic]  
  impsim = bugsOut$sims.array[,1,3+ic]  # 10000 imputations for every censor.
  impsim[1:3,]
  impsim[ic] 
  timp=t
  #
}
```


### 1-2 Figure 3-21(H) in the thesis.

```{r}
{
  # Kaplan-Meier Curve:
  curve1 = survfit(Surv(z,delta) ~ x); curve1
  plot(curve1, mark.time = TRUE,lty = 1,conf.int = FALSE,  col = "black",
       main = paste("H                  t~Weibull(2,4), c~Exp(0.06), p=0.20, n=200") ) 
  
  
  # Curve with Median of Simulated Times
  # output ----------------------------------------
  # imputation      h=hat
  bh = bugsOut$mean$b; bh
  shapeh = bugsOut$mean$shape; shapeh
  lambdah = exp(bh[1] + bh[2]*x); lambdah #every person has specific lambda because it has specific X.
  scaleh = lambdah^(-1/shapeh); scaleh
  # Compute median of Simulations.
  zmed = qweibull(.5*pweibull(cen,shapeh,scaleh, lower.tail = FALSE),shapeh, scaleh, lower.tail = FALSE)
  
  zimp = rep(NA,n)
  zimp[ic] = zmed[ic]
  zimp[-ic] = z[-ic]  # zimp = failure times+imputed censored times
  
  curve2 = survfit(Surv(zimp,delta1) ~ x); curve2     # Bayesian Imputation
  lines(curve2, mark.time = TRUE, col = "Blue", lty = 1)
  
  #Curve without Censored Times 
  tOC = z[delta==1]   #time omitting censored
  deltaOC = rep(1, length(tOC))
  curve3 = survfit(Surv(tOC, deltaOC) ~ x[delta==1]); curve3       # Omitting_Censored
  lines(curve3, mark.time = TRUE, col = "Red", lty = 1)
  
  legend("topright", c("Kaplan-Meier Curve", "Curve with Median of Simulated Times", "Curve without Censored Times"), lty= 1, col = c("black", "Blue", "Red"), cex = 0.7)
}
```

### 1-3 Figure 3-23(B) in the thesis.

```{r}

{  
  km1 = survfit(Surv(z,delta) ~ x); km1
  plot(km1, mark.time = TRUE,lty = 1, lwd =2, col = "black",
       main = paste("B                  t~Weibull(2,4), c~Exp(0.06), p=0.20, n=200"))  #KM_Estimation
  
  # simulation 
  for (i in 1:nrow(impsim)) {
    timp[ic] <- impsim[i,]
    kmi = survfit(Surv(timp,delta1) ~ x)
    lines(kmi, mark.time = TRUE, col = "gray", lty = 1)    # n time Imputation
    #Sys.sleep(.5)
  }
  timp[ic] <- colMeans(impsim)
  kmmean = survfit(Surv(timp,delta1) ~ x)
  lines(kmi, mark.time = TRUE, col = "blue", lty = 2, lwd = 2)  # Mean of n times Imputation
  
  lines(km1, mark.time = TRUE,lty = 1, lwd =2, col = "black",
        main = paste("B                  t~Weibull(2,4), c~Exp(0.06), p=0.20, n=200"))  #KM_Estimation
  
  legend("topright", 
         c("Kaplan-Meier Curve", "Curve for 10,000 Times Imputation", "Curve for Imputations Mean"),
         lty = 1, col = c("Black", "gray","blue"), cex = .7)
}  


```
